# Generated by Django 3.1.7 on 2021-08-17 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='in_store',
            field=models.BooleanField(default='True'),
        ),
    ]
